### ISSUE TITLE
Signature addition/support request

### ISSUE THREAD

**Issue by umlka** [Psykotikism/L4D1-2_Signatures#1]
/* nav_update_lighting(const CCommand *) */
"nav_update_lighting"
{
	"library"	"server"
	"linux"		"@_ZL19nav_update_lightingRK8CCommand"
	"windows"	"\x55\x8B\xEC\x8B\x45\x08\x57\x33\xFF\x83\x38\x02"
}
/* CNavArea::SpliceEdit(CNavArea*) */
"CNavArea::SpliceEdit"
{
	"library"	"server"
	"linux"		"@_ZN8CNavArea10SpliceEditEPS_"
	"windows"	"\x55\x8B\xEC\x83\xEC\x38\x53\x8B\x5D\x08\xF3\x0F\x10\x6B\x10"
}
/* IsAreaConnectedToNonCheckpointArea(TerrorNavArea *) */
"IsAreaConnectedToNonCheckpointArea"
{
	"library"	"server"
	"linux"		"@_Z34IsAreaConnectedToNonCheckpointAreaP13TerrorNavArea"
}

**Comment by Psykotikism** [comment]
Okay, I added these to the lists.

FYI, the "IsAreaConnectedToNonCheckpointArea" function is only supported in L4D2 since it's never called/referenced anywhere in L4D1. The other two functions are supported in both games.

Thanks for the Windows signatures. They helped me locate the functions faster.
